[tools]
darklua = { github = "seaofvoices/darklua", version = "=0.15.0"}
luau-lsp = { github = "JohnnyMorganz/luau-lsp", version = "=1.38.0"}
rojo = { github = "rojo-rbx/rojo", version = "=7.4.4"}
selene = { github = "Kampfkarren/selene", version = "=0.27.1"}
stylua = { github = "JohnnyMorganz/StyLua", version = "=2.0.2"}
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
