export type StudioStyleGuideColorStrings =
	"MainBackground"
	| "Titlebar"
	| "Dropdown"
	| "Tooltip"
	| "Notification"
	| "ScrollBar"
	| "ScrollBarBackground"
	| "TabBar"
	| "Tab"
	| "FilterButtonDefault"
	| "FilterButtonHover"
	| "FilterButtonChecked"
	| "FilterButtonAccent"
	| "FilterButtonBorder"
	| "FilterButtonBorderAlt"
	| "RibbonTab"
	| "RibbonTabTopBar"
	| "Button"
	| "MainButton"
	| "RibbonButton"
	| "ViewPortBackground"
	| "InputFieldBackground"
	| "Item"
	| "TableItem"
	| "CategoryItem"
	| "GameSettingsTableItem"
	| "GameSettingsTooltip"
	| "EmulatorBar"
	| "EmulatorDropDown"
	| "ColorPickerFrame"
	| "CurrentMarker"
	| "Border"
	| "DropShadow"
	| "Shadow"
	| "Light"
	| "Dark"
	| "Mid"
	| "MainText"
	| "SubText"
	| "TitlebarText"
	| "BrightText"
	| "DimmedText"
	| "LinkText"
	| "WarningText"
	| "ErrorText"
	| "InfoText"
	| "SensitiveText"
	| "ScriptSideWidget"
	| "ScriptBackground"
	| "ScriptText"
	| "ScriptSelectionText"
	| "ScriptSelectionBackground"
	| "ScriptFindSelectionBackground"
	| "ScriptMatchingWordSelectionBackground"
	| "ScriptOperator"
	| "ScriptNumber"
	| "ScriptString"
	| "ScriptComment"
	| "ScriptKeyword"
	| "ScriptBuiltInFunction"
	| "ScriptWarning"
	| "ScriptError"
	| "ScriptWhitespace"
	| "ScriptRuler"
	| "DocViewCodeBackground"
	| "DebuggerCurrentLine"
	| "DebuggerErrorLine"
	| "ScriptEditorCurrentLine"
	| "DiffFilePathText"
	| "DiffTextHunkInfo"
	| "DiffTextNoChange"
	| "DiffTextAddition"
	| "DiffTextDeletion"
	| "DiffTextSeparatorBackground"
	| "DiffTextNoChangeBackground"
	| "DiffTextAdditionBackground"
	| "DiffTextDeletionBackground"
	| "DiffLineNum"
	| "DiffLineNumSeparatorBackground"
	| "DiffLineNumNoChangeBackground"
	| "DiffLineNumAdditionBackground"
	| "DiffLineNumDeletionBackground"
	| "DiffFilePathBackground"
	| "DiffFilePathBorder"
	| "ChatIncomingBgColor"
	| "ChatIncomingTextColor"
	| "ChatOutgoingBgColor"
	| "ChatOutgoingTextColor"
	| "ChatModeratedMessageColor"
	| "Separator"
	| "ButtonBorder"
	| "ButtonText"
	| "InputFieldBorder"
	| "CheckedFieldBackground"
	| "CheckedFieldBorder"
	| "CheckedFieldIndicator"
	| "HeaderSection"
	| "Midlight"
	| "StatusBar"
	| "DialogButton"
	| "DialogButtonText"
	| "DialogButtonBorder"
	| "DialogMainButton"
	| "DialogMainButtonText"
	| "InfoBarWarningBackground"
	| "InfoBarWarningText"
	| "ScriptMethod"
	| "ScriptProperty"
	| "ScriptNil"
	| "ScriptBool"
	| "ScriptFunction"
	| "ScriptLocal"
	| "ScriptSelf"
	| "ScriptLuauKeyword"
	| "ScriptFunctionName"
	| "ScriptTodo"
	| "ScriptBracket"
	| "AttributeCog"

export type StudioStyleModifierStrings = "Default" | "Selected" | "Pressed" | "Disabled" | "Hover"

export type ColorStyleWrapper = ((StudioStyleModifierStrings | Enum.StudioStyleGuideModifier)?) -> Color3

export type Wrapper = {
	GetColor: (
		any,
		StudioStyleGuideColorStrings | Enum.StudioStyleGuideColor,
		(StudioStyleModifierStrings | Enum.StudioStyleGuideModifier)?
	) -> Color3,
	[Enum.StudioStyleGuideColor]: ColorStyleWrapper,
	MainBackground: ColorStyleWrapper,
	Titlebar: ColorStyleWrapper,
	Dropdown: ColorStyleWrapper,
	Tooltip: ColorStyleWrapper,
	Notification: ColorStyleWrapper,
	ScrollBar: ColorStyleWrapper,
	ScrollBarBackground: ColorStyleWrapper,
	TabBar: ColorStyleWrapper,
	Tab: ColorStyleWrapper,
	FilterButtonDefault: ColorStyleWrapper,
	FilterButtonHover: ColorStyleWrapper,
	FilterButtonChecked: ColorStyleWrapper,
	FilterButtonAccent: ColorStyleWrapper,
	FilterButtonBorder: ColorStyleWrapper,
	FilterButtonBorderAlt: ColorStyleWrapper,
	RibbonTab: ColorStyleWrapper,
	RibbonTabTopBar: ColorStyleWrapper,
	Button: ColorStyleWrapper,
	MainButton: ColorStyleWrapper,
	RibbonButton: ColorStyleWrapper,
	ViewPortBackground: ColorStyleWrapper,
	InputFieldBackground: ColorStyleWrapper,
	Item: ColorStyleWrapper,
	TableItem: ColorStyleWrapper,
	CategoryItem: ColorStyleWrapper,
	GameSettingsTableItem: ColorStyleWrapper,
	GameSettingsTooltip: ColorStyleWrapper,
	EmulatorBar: ColorStyleWrapper,
	EmulatorDropDown: ColorStyleWrapper,
	ColorPickerFrame: ColorStyleWrapper,
	CurrentMarker: ColorStyleWrapper,
	Border: ColorStyleWrapper,
	DropShadow: ColorStyleWrapper,
	Shadow: ColorStyleWrapper,
	Light: ColorStyleWrapper,
	Dark: ColorStyleWrapper,
	Mid: ColorStyleWrapper,
	MainTeColorStyleWrappert: ColorStyleWrapper,
	SubTeColorStyleWrappert: ColorStyleWrapper,
	TitlebarTeColorStyleWrappert: ColorStyleWrapper,
	BrightTeColorStyleWrappert: ColorStyleWrapper,
	DimmedTeColorStyleWrappert: ColorStyleWrapper,
	LinkTeColorStyleWrappert: ColorStyleWrapper,
	WarningTeColorStyleWrappert: ColorStyleWrapper,
	ErrorTeColorStyleWrappert: ColorStyleWrapper,
	InfoTeColorStyleWrappert: ColorStyleWrapper,
	SensitiveTeColorStyleWrappert: ColorStyleWrapper,
	ScriptSideWidget: ColorStyleWrapper,
	ScriptBackground: ColorStyleWrapper,
	ScriptTeColorStyleWrappert: ColorStyleWrapper,
	ScriptSelectionTeColorStyleWrappert: ColorStyleWrapper,
	ScriptSelectionBackground: ColorStyleWrapper,
	ScriptFindSelectionBackground: ColorStyleWrapper,
	ScriptMatchingWordSelectionBackground: ColorStyleWrapper,
	ScriptOperator: ColorStyleWrapper,
	ScriptNumber: ColorStyleWrapper,
	ScriptString: ColorStyleWrapper,
	ScriptComment: ColorStyleWrapper,
	ScriptKeyword: ColorStyleWrapper,
	ScriptBuiltInFunction: ColorStyleWrapper,
	ScriptWarning: ColorStyleWrapper,
	ScriptError: ColorStyleWrapper,
	ScriptWhitespace: ColorStyleWrapper,
	ScriptRuler: ColorStyleWrapper,
	DocViewCodeBackground: ColorStyleWrapper,
	DebuggerCurrentLine: ColorStyleWrapper,
	DebuggerErrorLine: ColorStyleWrapper,
	ScriptEditorCurrentLine: ColorStyleWrapper,
	DiffFilePathTeColorStyleWrappert: ColorStyleWrapper,
	DiffTeColorStyleWrappertHunkInfo: ColorStyleWrapper,
	DiffTeColorStyleWrappertNoChange: ColorStyleWrapper,
	DiffTeColorStyleWrappertAddition: ColorStyleWrapper,
	DiffTeColorStyleWrappertDeletion: ColorStyleWrapper,
	DiffTeColorStyleWrappertSeparatorBackground: ColorStyleWrapper,
	DiffTeColorStyleWrappertNoChangeBackground: ColorStyleWrapper,
	DiffTeColorStyleWrappertAdditionBackground: ColorStyleWrapper,
	DiffTeColorStyleWrappertDeletionBackground: ColorStyleWrapper,
	DiffLineNum: ColorStyleWrapper,
	DiffLineNumSeparatorBackground: ColorStyleWrapper,
	DiffLineNumNoChangeBackground: ColorStyleWrapper,
	DiffLineNumAdditionBackground: ColorStyleWrapper,
	DiffLineNumDeletionBackground: ColorStyleWrapper,
	DiffFilePathBackground: ColorStyleWrapper,
	DiffFilePathBorder: ColorStyleWrapper,
	ChatIncomingBgColor: ColorStyleWrapper,
	ChatIncomingTeColorStyleWrappertColor: ColorStyleWrapper,
	ChatOutgoingBgColor: ColorStyleWrapper,
	ChatOutgoingTeColorStyleWrappertColor: ColorStyleWrapper,
	ChatModeratedMessageColor: ColorStyleWrapper,
	Separator: ColorStyleWrapper,
	ButtonBorder: ColorStyleWrapper,
	ButtonTeColorStyleWrappert: ColorStyleWrapper,
	InputFieldBorder: ColorStyleWrapper,
	CheckedFieldBackground: ColorStyleWrapper,
	CheckedFieldBorder: ColorStyleWrapper,
	CheckedFieldIndicator: ColorStyleWrapper,
	HeaderSection: ColorStyleWrapper,
	Midlight: ColorStyleWrapper,
	StatusBar: ColorStyleWrapper,
	DialogButton: ColorStyleWrapper,
	DialogButtonTeColorStyleWrappert: ColorStyleWrapper,
	DialogButtonBorder: ColorStyleWrapper,
	DialogMainButton: ColorStyleWrapper,
	DialogMainButtonTeColorStyleWrappert: ColorStyleWrapper,
	InfoBarWarningBackground: ColorStyleWrapper,
	InfoBarWarningTeColorStyleWrappert: ColorStyleWrapper,
	ScriptMethod: ColorStyleWrapper,
	ScriptProperty: ColorStyleWrapper,
	ScriptNil: ColorStyleWrapper,
	ScriptBool: ColorStyleWrapper,
	ScriptFunction: ColorStyleWrapper,
	ScriptLocal: ColorStyleWrapper,
	ScriptSelf: ColorStyleWrapper,
	ScriptLuauKeyword: ColorStyleWrapper,
	ScriptFunctionName: ColorStyleWrapper,
	ScriptTodo: ColorStyleWrapper,
	ScriptBracket: ColorStyleWrapper,
	AttributeCog: ColorStyleWrapper,
}

return nil
