export type StudioStyleGuideColorStrings =
	"MainBackground"
	| "Titlebar"
	| "Dropdown"
	| "Tooltip"
	| "Notification"
	| "ScrollBar"
	| "ScrollBarBackground"
	| "TabBar"
	| "Tab"
	| "FilterButtonDefault"
	| "FilterButtonHover"
	| "FilterButtonChecked"
	| "FilterButtonAccent"
	| "FilterButtonBorder"
	| "FilterButtonBorderAlt"
	| "RibbonTab"
	| "RibbonTabTopBar"
	| "Button"
	| "MainButton"
	| "RibbonButton"
	| "ViewPortBackground"
	| "InputFieldBackground"
	| "Item"
	| "TableItem"
	| "CategoryItem"
	| "GameSettingsTableItem"
	| "GameSettingsTooltip"
	| "EmulatorBar"
	| "EmulatorDropDown"
	| "ColorPickerFrame"
	| "CurrentMarker"
	| "Border"
	| "DropShadow"
	| "Shadow"
	| "Light"
	| "Dark"
	| "Mid"
	| "MainText"
	| "SubText"
	| "TitlebarText"
	| "BrightText"
	| "DimmedText"
	| "LinkText"
	| "WarningText"
	| "ErrorText"
	| "InfoText"
	| "SensitiveText"
	| "ScriptSideWidget"
	| "ScriptBackground"
	| "ScriptText"
	| "ScriptSelectionText"
	| "ScriptSelectionBackground"
	| "ScriptFindSelectionBackground"
	| "ScriptMatchingWordSelectionBackground"
	| "ScriptOperator"
	| "ScriptNumber"
	| "ScriptString"
	| "ScriptComment"
	| "ScriptKeyword"
	| "ScriptBuiltInFunction"
	| "ScriptWarning"
	| "ScriptError"
	| "ScriptWhitespace"
	| "ScriptRuler"
	| "DocViewCodeBackground"
	| "DebuggerCurrentLine"
	| "DebuggerErrorLine"
	| "ScriptEditorCurrentLine"
	| "DiffFilePathText"
	| "DiffTextHunkInfo"
	| "DiffTextNoChange"
	| "DiffTextAddition"
	| "DiffTextDeletion"
	| "DiffTextSeparatorBackground"
	| "DiffTextNoChangeBackground"
	| "DiffTextAdditionBackground"
	| "DiffTextDeletionBackground"
	| "DiffLineNum"
	| "DiffLineNumSeparatorBackground"
	| "DiffLineNumNoChangeBackground"
	| "DiffLineNumAdditionBackground"
	| "DiffLineNumDeletionBackground"
	| "DiffFilePathBackground"
	| "DiffFilePathBorder"
	| "ChatIncomingBgColor"
	| "ChatIncomingTextColor"
	| "ChatOutgoingBgColor"
	| "ChatOutgoingTextColor"
	| "ChatModeratedMessageColor"
	| "Separator"
	| "ButtonBorder"
	| "ButtonText"
	| "InputFieldBorder"
	| "CheckedFieldBackground"
	| "CheckedFieldBorder"
	| "CheckedFieldIndicator"
	| "HeaderSection"
	| "Midlight"
	| "StatusBar"
	| "DialogButton"
	| "DialogButtonText"
	| "DialogButtonBorder"
	| "DialogMainButton"
	| "DialogMainButtonText"
	| "InfoBarWarningBackground"
	| "InfoBarWarningText"
	| "ScriptMethod"
	| "ScriptProperty"
	| "ScriptNil"
	| "ScriptBool"
	| "ScriptFunction"
	| "ScriptLocal"
	| "ScriptSelf"
	| "ScriptLuauKeyword"
	| "ScriptFunctionName"
	| "ScriptTodo"
	| "ScriptBracket"
	| "AttributeCog"

export type StudioStyleModifierStrings = "Default" | "Selected" | "Pressed" | "Disabled" | "Hover"

export type ModifierWrapper = typeof(setmetatable({}, {
	__index = {} :: {
		MainBackground: Color3,
		Titlebar: Color3,
		Dropdown: Color3,
		Tooltip: Color3,
		Notification: Color3,
		ScrollBar: Color3,
		ScrollBarBackground: Color3,
		TabBar: Color3,
		Tab: Color3,
		FilterButtonDefault: Color3,
		FilterButtonHover: Color3,
		FilterButtonChecked: Color3,
		FilterButtonAccent: Color3,
		FilterButtonBorder: Color3,
		FilterButtonBorderAlt: Color3,
		RibbonTab: Color3,
		RibbonTabTopBar: Color3,
		Button: Color3,
		MainButton: Color3,
		RibbonButton: Color3,
		ViewPortBackground: Color3,
		InputFieldBackground: Color3,
		Item: Color3,
		TableItem: Color3,
		CategoryItem: Color3,
		GameSettingsTableItem: Color3,
		GameSettingsTooltip: Color3,
		EmulatorBar: Color3,
		EmulatorDropDown: Color3,
		ColorPickerFrame: Color3,
		CurrentMarker: Color3,
		Border: Color3,
		DropShadow: Color3,
		Shadow: Color3,
		Light: Color3,
		Dark: Color3,
		Mid: Color3,
		MainTeColorStyleWrappert: Color3,
		SubTeColorStyleWrappert: Color3,
		TitlebarTeColorStyleWrappert: Color3,
		BrightTeColorStyleWrappert: Color3,
		DimmedTeColorStyleWrappert: Color3,
		LinkTeColorStyleWrappert: Color3,
		WarningTeColorStyleWrappert: Color3,
		ErrorTeColorStyleWrappert: Color3,
		InfoTeColorStyleWrappert: Color3,
		SensitiveTeColorStyleWrappert: Color3,
		ScriptSideWidget: Color3,
		ScriptBackground: Color3,
		ScriptTeColorStyleWrappert: Color3,
		ScriptSelectionTeColorStyleWrappert: Color3,
		ScriptSelectionBackground: Color3,
		ScriptFindSelectionBackground: Color3,
		ScriptMatchingWordSelectionBackground: Color3,
		ScriptOperator: Color3,
		ScriptNumber: Color3,
		ScriptString: Color3,
		ScriptComment: Color3,
		ScriptKeyword: Color3,
		ScriptBuiltInFunction: Color3,
		ScriptWarning: Color3,
		ScriptError: Color3,
		ScriptWhitespace: Color3,
		ScriptRuler: Color3,
		DocViewCodeBackground: Color3,
		DebuggerCurrentLine: Color3,
		DebuggerErrorLine: Color3,
		ScriptEditorCurrentLine: Color3,
		DiffFilePathTeColorStyleWrappert: Color3,
		DiffTeColorStyleWrappertHunkInfo: Color3,
		DiffTeColorStyleWrappertNoChange: Color3,
		DiffTeColorStyleWrappertAddition: Color3,
		DiffTeColorStyleWrappertDeletion: Color3,
		DiffTeColorStyleWrappertSeparatorBackground: Color3,
		DiffTeColorStyleWrappertNoChangeBackground: Color3,
		DiffTeColorStyleWrappertAdditionBackground: Color3,
		DiffTeColorStyleWrappertDeletionBackground: Color3,
		DiffLineNum: Color3,
		DiffLineNumSeparatorBackground: Color3,
		DiffLineNumNoChangeBackground: Color3,
		DiffLineNumAdditionBackground: Color3,
		DiffLineNumDeletionBackground: Color3,
		DiffFilePathBackground: Color3,
		DiffFilePathBorder: Color3,
		ChatIncomingBgColor: Color3,
		ChatIncomingTeColorStyleWrappertColor: Color3,
		ChatOutgoingBgColor: Color3,
		ChatOutgoingTeColorStyleWrappertColor: Color3,
		ChatModeratedMessageColor: Color3,
		Separator: Color3,
		ButtonBorder: Color3,
		ButtonTeColorStyleWrappert: Color3,
		InputFieldBorder: Color3,
		CheckedFieldBackground: Color3,
		CheckedFieldBorder: Color3,
		CheckedFieldIndicator: Color3,
		HeaderSection: Color3,
		Midlight: Color3,
		StatusBar: Color3,
		DialogButton: Color3,
		DialogButtonTeColorStyleWrappert: Color3,
		DialogButtonBorder: Color3,
		DialogMainButton: Color3,
		DialogMainButtonTeColorStyleWrappert: Color3,
		InfoBarWarningBackground: Color3,
		InfoBarWarningTeColorStyleWrappert: Color3,
		ScriptMethod: Color3,
		ScriptProperty: Color3,
		ScriptNil: Color3,
		ScriptBool: Color3,
		ScriptFunction: Color3,
		ScriptLocal: Color3,
		ScriptSelf: Color3,
		ScriptLuauKeyword: Color3,
		ScriptFunctionName: Color3,
		ScriptTodo: Color3,
		ScriptBracket: Color3,
		AttributeCog: Color3,
	},
	__call = function(_, style: StudioStyleGuideColorStrings | Enum.StudioStyleGuideColor): Color3
		return Color3.new()
	end,
}))

export type Wrapper = {
	GetColor: (
		any,
		StudioStyleGuideColorStrings | Enum.StudioStyleGuideColor,
		(StudioStyleModifierStrings | Enum.StudioStyleGuideModifier)?
	) -> Color3,
	[Enum.StudioStyleGuideModifier]: ModifierWrapper,
	Default: ModifierWrapper,
	Selected: ModifierWrapper,
	Pressed: ModifierWrapper,
	Disabled: ModifierWrapper,
	Hover: ModifierWrapper,
}

return nil
