return {
	Background = require(script.Background),
	Button = require(script.Button),
	Checkbox = require(script.Checkbox),
	ColorPicker = require(script.ColorPicker),
	Dropdown = require(script.Dropdown),
	Label = require(script.Label),
	MainButton = require(script.MainButton),
	ScrollFrame = require(script.ScrollFrame),
	Slider = require(script.Slider),
	TabContainer = require(script.TabContainer),
	TextInput = require(script.TextInput),
	VerticalCollapsibleSection = require(script.VerticalCollapsibleSection),
	VerticalExpandingList = require(script.VerticalExpandingList),
	Widget = require(script.Widget),
	ThemeContext = require(script.ThemeContext),
	withTheme = require(script.withTheme),
	useTheme = require(script.useTheme),
}
